### ISSUE TITLE
Some objects are missing scaling in levels

### ISSUE THREAD

**Issue by azdful** [Puxtril/Warframe-Exporter#39]
Lotus/Levels/TheNewWar2021/PartOne/TNWRJRedNebula/RedNebulaRegionEmpty.level
![изображение](https://github.com/user-attachments/assets/e62ca7f6-5419-4435-8a4e-abbcb2a111a5)
↑ how it looks
↓ how it's supposed to look like
![изображение](https://github.com/user-attachments/assets/7495c466-4668-4472-8894-c37c80265b59)

**Comment by Puxtril** [comment]
For me, this level fails to import into Blender. I'm pretty sure it's because there's an error with `/Lotus/Objects/Guild/Ships/CrpStanchionShipV2/CrpStanchionShipBanners.fbx`. Will check it out tomorrow.

**Comment by Puxtril** [comment]
Seems to be related to #27. The models with incorrect scale have "Attached=1", which is shared by models in the linked issue.

But the issue referenced in my previous comment has been fixed in fed10523dd3fe7f46989da5914644abe2c989138. More models are now extracted, and I can  import into Blender without error.
